apiVersion: apps/v1
kind: Deployment
metadata:
  name: amdsimplemultiarchapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: amdsimplemultiarchapp
  template:
    metadata:
      labels:
        app: amdsimplemultiarchapp
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: tlvsummit23amd
      serviceAccountName: appsimulator
      containers:
      - name: app
        env:
        - name: ARCH
          value: "amd64"
        - name: CW_NS
          value: "appsimulator"
        - name: MATRIX_DIM
          value: "500"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/simplemultiarchimage:multiarch-py3
        imagePullPolicy: Always
        command: ["/usr/src/app/start.sh"]
        resources:
          requests:
            cpu: 1000m
          limits:
            cpu: 4000m
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /app/health/
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /app/health/
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
