apiVersion: batch/v1
kind: Job
metadata:
  name: initdb
spec:
  template:
    spec:
     nodeSelector:
        karpenter.sh/provisioner-name: default
     containers:
      - name: initdb
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/djangoapp:py39${INSTANCE_ARCH}64
        command: ["/usr/src/app/start.sh"]
      restartPolicy: Never
  backoffLimit: 4
